### ISSUE TITLE
Crash when a script that outputs multiple blocks times out

### ISSUE THREAD

**Issue by AlexAUT** [rei2hu/swayblocks#4]
Swayblocks often crashes when two modules ran into a timeout with `failed to parse i3bar json` as the visual error and cerr contains:

```
[23:19:24] [INFO] Timed out message recieved from ~/.config/swayblocks/scripts/wifi ["{\"separator_block_width\":\"10\",\"separator\":\"\",\"name\":\"~/.config/swayblocks/scripts/wifi\",\"instance\":0,\"full_text\":\" 10.0.0.8\",\"color\":\"#44ff44\",\"border\":\"#333333\"}", "{\"separator_block_width\":25,\"name\":\"~/.config/swayblocks/scripts/wifi\",\"instance\":1,\"full_text\":\" 46.0%\",\"color\":\"#A8FF00\",\"border\":\"#333333\"}"]
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (RuntimeError) no device registered with the name :user
        (logger) lib/logger/backends/console.ex:160: Logger.Backends.Console.async_io/2
        (logger) lib/logger/backends/console.ex:145: Logger.Backends.Console.log_event/5
        (logger) lib/logger/backends/console.ex:49: Logger.Backends.Console.handle_event/2
        (stdlib) gen_event.erl:577: :gen_event.server_update/4
        (stdlib) gen_event.erl:559: :gen_event.server_notify/4
        (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The first calls to wifi/volume take much longer after I unplug my laptop and are causing the timeouts, probably due to power saving hardware states

**Comment by rei2hu** [comment]
Sorry about the delay in responding, I didn't receive a notification for some reason.

I'm unable to reproduce the behaviour with a few scripts to force timeouts like
```
#!/bin/bash
sleep 10
echo "full_text:$RANDOM"
```
I've seen that error before which occurs when swaybar dies and swayblocks tries sending a message so I imagine that invalid JSON is pushed to it somehow which kills it which then results in the error when swayblocks tries to send a message.

If you can reliably reproduce the problem, could you check the output to swaybar by using `tee` e.g.
`status_command swayblocks 2> .swayblocks.log | tee swayblocksstdout.log`? When swaybar crashes I assume the thing causing invalid json should be at the end of swayblocksstdout.log.

**Comment by AlexAUT** [comment]
[1] is the output during a crash. There is a "," missing between two blocks in the line before the error, do my scripts cause that or something in swayblocks?

[1]
```
{"version":1,"click_events":true}
[
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","instance":0,"full_text":" Muted"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":" 192.168.12.27","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":" 55.0%","color":"#69FF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","instance":0,"full_text":" 65%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","instance":0,"full_text":" (+, 100%)","color":"#00FF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","instance":0,"full_text":"Thu Nov 22, 2018 22:52:32"}],
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","instance":0,"full_text":" Muted"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":" 192.168.12.27","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":" 55.0%","color":"#69FF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","instance":0,"full_text":" 65%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","instance":0,"full_text":" (+, 100%)","color":"#00FF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","instance":0,"full_text":"Thu Nov 22, 2018 22:52:33"}],
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","instance":0,"full_text":" Muted"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":" 192.168.12.27","color":"#44ff44","border":"#333333"}{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":" 55.0%","color":"#69FF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","instance":0,"full_text":" 65%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","instance":0,"full_text":" (+, 100%)","color":"#00FF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","instance":0,"full_text":"Thu Nov 22, 2018 22:52:35"}],
 
22:52:35.144 [error] Process #PID<0.96.0> raised an exception
** (FunctionClauseError) no function clause matching in String.replace_prefix/3
    (elixir) lib/string.ex:937: String.replace_prefix(:eof, ",", "")
    (swayblocks) lib/input_handler.ex:11: InputHandler.listen/1
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","instance":0,"full_text":" Muted"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":" 192.168.12.27","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":" 55.0%","color":"#69FF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","instance":0,"full_text":" 65%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","instance":0,"full_text":" (+, 100%)","color":"#00FF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","instance":0,"full_text":"Thu Nov 22, 2018 22:52:36"}],
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","instance":0,"full_text":" Muted"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":" 192.168.12.27","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":" 54.0%","color":"#70FF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","instance":0,"full_text":" 65%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","instance":0,"full_text":" (+, 100%)","color":"#00FF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","instance":0,"full_text":"Thu Nov 22, 2018 22:52:37"}],
```

**Comment by rei2hu** [comment]
The missing comma between two blocks from the same script is most likely the problem, but it should have been fixed by 17f8773. It was reported recently at the bottom of #1 so you can try updating and that should be fixed.

I actually stopped using scripts that output multiple blocks so I didn't encounter the problem personally.

**Comment by AlexAUT** [comment]
I'm already using the latest master. Removing the second block from the script does indeed fix the issue, so it seems like #1 is not fixed for every case.

But i can live with splitting the scripts. Btw, thanks for your awesome work!

**Comment by rei2hu** [comment]
You were right after all; I wasn't joining the content from timed out scripts so it would crash if a script that outputs multiple blocks timed out. Thanks for the issue!

**Comment by AlexAUT** [comment]
Works now perfectly fine, thanks for the quick fix! Have a great weekend!
